### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by eMouses** [vin89423/wget-remote-downloader#1]
Hello.
The script writes an error
"/wget/ not found. (31)"

PHP Version 5.3.29
Help please.

**Comment by vin89423** [comment]
Seem like you didn't enable URL Re-write module.  Could you provide more detail.
I use this program almost every day & never see this error message.

**Comment by vin89423** [comment]
I know i am late for this reply, if you still using this app and not working under URL Rewrite module.
Could you show me your "manifest.json" file.

**Comment by eMouses** [comment]
URL Re-write module is enable

## my "manifest.json" file:

{
  "minPhpVersion": "5.0",
  "url": {
    "domain": "5588.ru",
    "root": "/wget/"
  },
  "session": {
    "token": "RD_TOKEN",
    "encrypt": "545454"
  },
  "application": {
    "activity": {
      "main": {
        "launch": "MainApp",
        "storage": "//",
        "languageSource": "ini",
        "language": [
          "zt",
          "en"
        ]
      }
    }
  }
}

**Comment by vin89423** [comment]
I checked you manifest.json is fine. Just url.root have an extra slash at the end but it won't produce the error you reached.

I see that the error come from the following code:

``` php
public function handler_default($url)
{
        $this->show_error(404, __LINE__);
}
```

When this function was called, it is because the browser request a url that cannot be found. If your .htaccess run well, it should not happen too. Can you capture and told me what Request URL the browser requesting.
