### ISSUE TITLE
Not able to login

### ISSUE THREAD

**Issue by P1-Ro** [vin89423/wget-remote-downloader#2]
I cant login because this error response gets returned from server: 

` {"status":"ERROR","data":"server_not_supported"}`

**Comment by vin89423** [comment]
Sorry for this super late reply.

Login feature in this project require **mcrypt_encrypt** module.
Please enable mod **mcrypt** in PHP.

On the other hand, empty **session_encrypt** in _startup.php_ will also cause this problem.
Please make sure the following part are set.

```php
$START_UP = array(
	'session' => array(
		'token' => 'RD_TOKEN',
		'encrypt' => 'here add 32char string as key',
	),
);
```

I have a update on its framework. it using startup.php instead of manifest.json.
